### ISSUE TITLE
Critics

### ISSUE THREAD

**Issue by mekas** [AtikahBZqAulia/Vviped#19]
- Where is the product backlog?
- Where are the sprint backlogs?
-

**Comment by AtikahBZqAulia** [comment]
Thank you for your feedback, Sir. We actually have stated our product backlog or key feature(s) in our README which is hate speech detection. And for the sprint backlogs we have done it as well in projects menu. https://github.com/AtikahBZqAulia/Vviped/projects/1

**Comment by AtikahBZqAulia** [comment]
You might want to see our product backlogs for each sprints in milestones along with previous closed milestone (Sprint 1 & Sprint 2) : https://github.com/AtikahBZqAulia/Vviped/milestones

**Comment by AtikahBZqAulia** [comment]
Here is our product backlogs : https://www.notion.so/0cb3638b1c284c1eb3f79f7f59e96a30?v=8cd37891c4d14f6fa1b0f9ca61ecf47a
as well as our sprint backlogs : https://github.com/AtikahBZqAulia/Vviped/issues
Thank you.
